version: '3.8'
services:
   website:
     container_name: website
     hostname: website
     image: nginx
     ports: 
     - "443:443"
     networks:
         website:
     working_dir: "/usr/share/nginx/html"
     volumes:
         - "./:/usr/share/nginx/html"
     restart: "unless-stopped"
networks:
  website:

